version: "3.4"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=root
    restart: always
    volumes:
      - mysql-container3:/var/lib/mysql:rw
    image: 'mysql:latest'
    
  projetdevops-backend:
    depends_on:
      - mysql-container3
    container_name: projetdevops-backend
    ports:
      - '8089:8089'
    image: hamzabelhajammar/projetdevops-backend


volumes:
  mysql-container3: { }